- name: Set a hostname to {{ host.name }} {{ task_identifier }}
  ansible.builtin.hostname:
    name: "{{ host.name }}"
    use: systemd

- name: Gather the package facts {{ task_identifier }} 
  ansible.builtin.package_facts:
    manager: auto

- set_fact:
    gnome_shell_current_major: "{{ ((ansible_facts.packages['gnome-shell'] | first).version).split('.') | first }}"

- name: Add git settings to ~/.gitconfig {{ task_identifier }}
  community.general.git_config:
    name: "{{ git_config.name }}"
    scope: "{{ git_config.scope }}"
    value: "{{ git_config.value }}"
  loop: "{{ host.git_config }}"
  loop_control:
    loop_var: git_config

# remove and instead downlaod directly from URLs
- name: Download local binary packages {{ task_identifier }}
  get_url:
    url: "{{ app.url }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ app.name }}"
    mode: a+x
  register: bin
  loop_control:
    loop_var: app
  loop: "{{ host.local_packages.bins }}"
  retries: 15
  delay: 30
  until: bin.failed == False

- name: Download local binary archive {{ task_identifier }}
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ app.url }}"
    dest: "{{ ansible_user_dir }}/.local/bin/"
    include: "{{ app.exclude | default([]) }}"
    mode: a+x
  loop_control:
    loop_var: app
  loop: "{{ host.local_packages.archives }}"
