- name: Ensure {{ toolbox.name }} toolbox is created and started
  shell: "{{ toolbox_bootstrap }}"
  register: toolbox_create
  changed_when: false
  failed_when:
    - toolbox_create.rc != 0
    - "'already exists' not in toolbox_create.stderr"
  loop:
    - toolbox create --image {{ toolbox.image }} {{ toolbox.name }} -y
    - podman start {{ toolbox.name }}
  loop_control:
    loop_var: toolbox_bootstrap
  when: toolbox.sandbox_tool == "toolbox"

- name: Ensure {{ toolbox.name }} home directory is present
  ansible.builtin.file:
    path: "{{ toolbox.home }}"
    state: directory
    mode: '0755'
  when:
    - toolbox.sandbox_tool == "distrobox"
    - toolbox.home is defined

- name: Ensure {{ toolbox.name }} distrobox is created and started
  shell: "{{ toolbox_bootstrap }}"
  register: toolbox_create
  changed_when: false
  failed_when:
    - toolbox_create.rc != 0
    - "'already exists' not in toolbox_create.stderr"
  loop:
    - >
      distrobox create --image {{ toolbox.image }} --name {{ toolbox.name }}
      {{ ('--home' + ' ' + toolbox.home) if toolbox.home is defined else '' }}
      {{ ('--additional-flags' + ' ' + toolbox.additional_flags) if toolbox.additional_flags is defined else '' }}
    - podman start {{ toolbox.name }}
  loop_control:
    loop_var: toolbox_bootstrap
  when: toolbox.sandbox_tool == "distrobox"

- name: Execute host tasks for toolbox {{ toolbox.name }}
  include_tasks: "{{ task }}"
  loop: "{{ toolbox.host_tasks | default([]) }}"
  loop_control:
    loop_var: task
  vars:
    task_identifier: "(Toolbox: {{ toolbox.name }})"

- name: Gather container {{ toolbox.name }} facts
  containers.podman.podman_container_info:
    name: ["{{ toolbox.name }}"]
  register: toolbox_facts

- name: Add container {{ toolbox.name }} as ansible host
  ansible.builtin.add_host:
    name: "{{ (toolbox_facts.containers | first).Name }}"
    ansible_host: "{{ (toolbox_facts.containers | first).Id }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: podman
    groups: toolbox
  changed_when: false

- name: Execute tasks on {{ toolbox.name }} toolbox container
  delegate_to: "{{ toolbox.name }}"
  delegate_facts: true
  block:
    - name: Run tasks on {{ toolbox.name }} container
      include_tasks: "{{ task }}"
      loop: "{{ toolbox.sandbox_tasks }}"
      loop_control:
        loop_var: task
      vars:
        task_identifier: "(Toolbox: {{ toolbox.name }})"
