- name: Create toolbox-runner links {{ task_identifier }}
  ansible.builtin.template:
    src: toolbox-runner.tpl
    mode: a+x
    dest: "{{ lookup('env','HOME') }}/.local/bin/{{ cmd }}"
  vars:
    container: "{{ toolbox.name }}"
  loop: "{{ toolbox.cmds | default([]) }}"
  loop_control:
    loop_var: cmd
