- name: Install software {{ task_identifier }}
  ansible.builtin.dnf:
    state: present
    name: "{{ package }}"
  loop: "{{ toolbox.packages | default([]) }}"
  loop_control:
    loop_var: package

- name: Make users passwordless for sudo in group wheel {{ task_identifier }}
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
