remotes:
  - name: fedora
    state: present
    flatpakrepo_url: oci+https://registry.fedoraproject.org
    method: system

  - name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

  - name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    method: user

flatpaks:
  - name: org.gnome.FileRoller
    state: absent
    method: system
    remote: fedora

  - name: org.gnome.Extensions
    state: present
    method: system
    remote: fedora

  - name: org.gnome.TextEditor
    state: present
    method: user
    remote: flathub-beta
    cmds: [gtedit, gnome-text-editor]

  - name: org.gimp.GIMP
    state: present
    method: system
    remote: flathub
    cmds: [gimp]

  - name: org.gnome.gedit
    state: present
    method: user
    remote: flathub
    cmds: [gedit]

  - name: com.slack.Slack
    state: present
    method: user
    remote: flathub
    cmds: [slack]

  - name: org.telegram.desktop
    state: present
    method: user
    remote: flathub
    cmds: [telegram]

#  - name: io.neovim.nvim
#    state: present
#    method: user
#    remote: flathub
#    cmds: [vi, vim, nvim]
#    overrides:
#      - { name: "--filesystem=/tmp", scope: user }
#      - { name: "--env=TERM=xterm-256color", scope: user }

  - name: com.brave.Browser
    state: present
    method: user
    remote: flathub-beta
    cmds: [brave]
    overrides:
      - { name: "--filesystem=~/.local/share/applications", scope: user }
      - { name: "--filesystem=~/.local/share/icons", scope: user }

  - name: org.keepassxc.KeePassXC
    state: present
    method: user
    remote: flathub
    cmds: [keepassxc]
