- key: /org/gnome/desktop/wm/preferences/button-layout
  value: "appmenu:minimize,maximize,close"
  single_quoted: yes 
- key: /org/gnome/desktop/wm/preferences/focus-mode
  value: click
  single_quoted: yes
- key: /org/gnome/desktop/sound/allow-volume-above-100-percent
  value: "true" 
- key: /org/gnome/desktop/interface/clock-format
  value: 24 
- key: /org/gnome/desktop/interface/show-battery-percentage
  value: "true" 
- key: /org/gnome/desktop/interface/clock-show-weekday
  value: "true" 
- key: /org/gnome/desktop/interface/clock-show-seconds
  value: "true"
- key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
  value: "true"
- key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
  value: "true" 
- key: /org/gnome/desktop/peripherals/touchpad/disable-while-typing
  value: "true" 
- key: /org/gnome/shell/extensions/caffeine/inhibit-apps
  value: "['com.brave.Browser.desktop']"
- key: /org/gnome/shell/extensions/dash-to-panel/panel-positions
  value: '{"0":"TOP","1":"TOP","2":"TOP","3":"TOP"}'
  single_quoted: yes 
- key: /org/gnome/shell/extensions/clipboard-indicator/history-size
  value: 60 
- key: /org/gnome/shell/extensions/clipboard-indicator/move-item-first
  value: "true" 

